feature Parasite Hub
TAARG-Education/F2Rotor pull request #14
Opened 2024-06-11 16:51 UTC by ariannapa

Python function

2024-07-22 08:11 UTC, EttoreSaetta requested changes
You removed the other functions.
Fix it!

2024-07-22 08:20 UTC, ariannapa commented
﻿
﻿
Buongiorno, posso risolvere rimettendo le funzioni nella cartella dedicata, giusto? Avevo citato questo problema nell’email  di martedì.
Cordiali saluti.

Il giorno 22 lug 2024, alle ore 10:12, SaettaE ***@***.***> ha scritto:

﻿

@EttoreSaetta requested changes on this pull request.

You removed the other functions.
Fix it!

—
Reply to this email directly, view it on GitHub<https://github.com/TAARG-Education/F2Rotor/pull/14#pullrequestreview-2190918892>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BHWQ34HFQHMFFWE5JKC4BI3ZNS5GFAVCNFSM6AAAAABJEXFYIOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOJQHEYTQOBZGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-22 17:07 UTC, EttoreSaetta requested changes

2024-07-22 17:07 UTC, EttoreSaetta commented on Helicopter_Class.py
>          # Developing the possibility of integration within the feature_geometry
Are you sure these should be removed?

2024-09-07 09:47 UTC, EttoreSaetta requested changes
Changes requested!

Also need a test case for your function.

2024-09-07 09:47 UTC, EttoreSaetta commented on parasite_hub.py
> +    def hub(self):
Remove indentation.
Self is used within the classes, rename your input.

2024-09-07 09:47 UTC, EttoreSaetta commented on parasite_hub.py
> +        -S: reference area
Seems the input is wrong.
It looks like you only have 1 input variable you named "self".

2024-09-09 13:23 UTC, EttoreSaetta approved these changes
LGTM

2024-09-09 13:23 UTC, merged