feature BEMT Rotor Hover
TAARG-Education/F2Rotor pull request #3
Opened 2024-05-18 07:17 UTC by francescogervasio

BEMT is a method that executes the blade element momentum theory. It accepts as input some data of the
  helicopter's rotor, specifically:

  Altitude: the altitude at which the helicopter is hovering (m)
  V_infty: the helicopter horizontal fligth speed (m/s)
  MTOW: Maximum Take-Off Weight of the helicopter (kg);
  R_mr: main rotor radius (m);
  R_hub: rotor hub radius(m);
  c_mr: chord of the main rotor's blade (m);
  N_mr: number of blades;
  theta0: pitch angle at the root of the rotor (°);
  theta_tw: blade twist (tip minus root incidence) (°);
  Cla: lift curve slope of the adopted airfoil (1/rad);
  Cd0: profile drag coefficient of the adopted airfoil.

  It gives as output:

  Tc: Thrust coefficient;
  T: Thrust (N);
  Qc: Torque (Power) coefficient;
  Q: Torque (Nm);
  Tc_PR: Thrust coefficient (considering the Prandtl correction function);
  T_PR: Thrust (considering the Prandtl correction function) (N);
  Qc_PR: Torque (Power) coefficient (considering the Prandtl correction function);
  Q_PR: Torque (considering the Prandtl correction function) (Nm);
  P: Power  (W);
  P_PR: Power (considering the Prandtl correction function) (W);
  Pc_i: Induced Power coefficient;
  P_i: Induced Power (W);
  Pc_0: Parasite Power coefficient;
  P_0: Parasite Power (W);
  FM: Figure of Merit;
  FM_PR: Figure of Merit (considering the Prandtl correction function);
  Disk_Loading: Disk Loading T/A (N/m^2);
  Power_Loading: Power Loading T/P (N/W);
  lambda_i: Induced inflow ratio distribution along the main rotor radius;
  alpha: angle of attack distribution along the main rotor radius (rad);
  dTcdr_bar: Thrust coefficient distribution along the adimensionalized main rotor radius;
  dQcdr_bar: Torque (Power) coefficient distribution along the adimensionalized main rotor radius;
  dTcdr_bar_PR: Thrust coefficient distribution along the adimensionalized main rotor radius (considering the Prandtl
  correction function);
  dQcdr_bar_PR: Torque (Power) coefficient distribution along the adimensionalized main rotor radius (considering the
  Prandtl correction function);
  r_bar: dimensional stations along the main rotor radius (m).

2024-05-21 18:18 UTC, EttoreSaetta requested changes
Make these changes before merging.

2024-05-21 18:18 UTC, EttoreSaetta commented on BEMT_Hover.py
> +        C1 = mu + Cla * sol / 8  # First degree coefficient
Move outside the loop

2024-05-21 18:18 UTC, EttoreSaetta commented on BEMT_Hover.py
> +    for j in range(len(r_bar)):
You can try vectorizing this loop

2024-05-21 18:18 UTC, EttoreSaetta commented on BEMT_Hover.py
> +        print(dTcdr_bar_PR[j])
Remove print

2024-05-21 18:18 UTC, EttoreSaetta commented on BEMT_Hover.py
> +    FM_PR = ((Tc_PR ** (3 / 2) / np.sqrt(2))) / Qc_PR  # Figure of Merit considering the Prandtl correction function
You can avoid computing `Tc`, `Qc` and `FM` with Prandtl's correction.
Just provide in output the uncorrected distributions and the `F_prandtl`.

2024-05-23 13:48 UTC, rtogna requested changes

2024-05-23 13:48 UTC, rtogna commented on BEMT_Hover.py
> +    """BEMT_Hover is a method that executes the Blade Element Momentum Theory with respect for an helicopter in hover or
Nel commento iniziale inserire:
dove trovare la teoria es.: R. Tognaccini,....., p. xyz
autore, data, versione

2024-05-23 14:19 UTC, EttoreSaetta approved these changes

2024-05-23 14:21 UTC, merged