feature Counter-Rotating Forward Flight
TAARG-Education/F2Rotor pull request #58
Opened 2024-12-13 11:23 UTC by DaniloSchioppa

2024-12-13 11:57 UTC, DaniloSchioppa commented
This function calculates the various power components required for the flight of an helicopter, with counter rotating coaxial configuration, based on the provided input parameters.

The outputs include:
- Total Power Required (P_old): the sum of all power components necessary to sustain flight;
- Induced Power (P_i_old): the power contribution required to generate lift, accounting for the induced velocity created by the rotor during flight;
- Profile Power (P_0_old): the power expended to overcome the aerodynamic drag of the rotor blades;
- Fuselage Power (P_fus_old): the power needed to counteract the aerodynamic drag of the vehicle fuselage.

The required inputs for these calculations are:
- Flight speed (V_inf): the airspeed relative to the vehicle;
- Number of rotors (N_contra): the number of rotors installed on the vehicle;
- Rotor radius (R): the length from the center to the tip of the rotor blades;
- Vehicle mass (M): the total weight of the aircraft;
- Hover induced velocity (w_h): the airflow velocity induced by the rotors during hover;
- Altitude (height): the height above sea level, used to determine air density;
- Equivalent area (f): a parameter representing the vehicle’s total drag area;
- Angular velocity (Omega): the rotational speed of the rotors;
- Hover induced power coefficient (Pci_h): defined as Tc^(3/2)/rad(2) ;
- Hover profile power coefficient (Pc0_h): defined as  (σ Cd )/ 8 .

2024-12-16 11:09 UTC, EttoreSaetta requested changes
Solve the following points:

1. header at the beginning of the .py file is missing.
2. Test Cases missing.
3. Follow the comments below:

2024-12-16 11:09 UTC, EttoreSaetta commented on ContraFW.py
> +            return 0.36391 * np.exp(-0.0001577 * (h - 11000))
Use the `ambiance` library for the ISA calculations

2024-12-16 11:09 UTC, EttoreSaetta commented on ContraFW.py
> +print("Fuselage Power (P_fus_old):", P_fus_old)
Remove `print()` in the function

2024-12-17 18:41 UTC, EttoreSaetta approved these changes

2024-12-17 18:42 UTC, merged